name: Build & Deploy to GitHub Pages

# Run this workflow on push to main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - uses: actions/checkout@v4

      # 2. Set up Node.js (adjust version if needed)
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - run: npm ci

      # 4. Build the site
      - run: npm run build

      # 5. Deploy the `dist/` folder to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
